backend:
  name: git-gateway
  branch: main

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "data/cars.json"
        label: "cars.json"
        name: "cars"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json" }