backend:
  name: git-gateway
  branch: main

publish_mode: simple

collections:
  - name: "data"
    label: "Δεδομένα"
    files:
      - file: "data/cars.json"
        label: "cars.json"
        name: "cars"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json" }
