backend:
  name: git-gateway
  branch: main

publish_mode: simple

# ΑΠΑΙΤΟΥΜΕΝΑ για να μην πετάει schema error
media_folder: "KazaltzisCars/uploads"
public_folder: "/uploads"

collections:
  - name: "data"
    label: "Δεδομένα"
    files:
      - file: "KazaltzisCars/data/cars.json"
        label: "cars.json"
        name: "cars"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "JSON"
            name: "body"
            widget: "code"
            default_language: "json"
